FROM eclipse-temurin:21-jdk
WORKDIR /workspace

COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle settings.gradle ./
RUN chmod +x gradlew

RUN ./gradlew dependencies

COPY src src
EXPOSE 8080

CMD ["./gradlew", "bootRun"]
